### ISSUE TITLE
Application version info

### ISSUE THREAD

**Issue by werberson** [labbsr0x/big-brother#12]
According to the big-brother protocol, the application version info is set as histogram and counter labels.
e.g.
```prometheus
request_seconds_bucket{type="http",status="404",method="GET",addr="/app", version="1.0.1",isError="true",le="1.0",} 2.0
```

GO and other systems use a pattern to collect and expose the application version, collecting as a gauge metric with the version info label and the gauge value set to 1.
The pattern is described in [this post](https://www.robustperception.io/exposing-the-software-version-to-prometheus).

e.g.
```prometheus
application_info{version="v1.0.1"} 1
```

I think It would be interesting to big-brother follows the same pattern.

**Comment by abilioesteves** [comment]
I agree with you. I will update the protocol and open the issues at `express-monitor` and `servlet-monitor` libs.
