### ISSUE TITLE
Possibilidade de adicionar descrição ao DependencyChecker

### ISSUE THREAD

**Issue by rogerio-dasilva** [labbsr0x/big-brother#13]
Avaliar a possibilidade de adicionar descrição no resultado de DependencyChecker.run(), principalmente se DependencyState for DOWN.

Por exemplo, quando ocorrer uma Exception, na execução de run(), capturar a Exception e usar getMessage() para usar na descrição.

Ou, caso o usuário da api deseje, adicionar mais informação no retorno de DependencyState.

**Comment by abilioesteves** [comment]
@werberson e @rogerio-dasilva, acredito que isso quebra a premissa inicial de métricas que é "expor sintomas de falha". Para análises de causa raíz, por favor utilizar logs.
