### ISSUE TITLE
Create Grafana's dashboard based on Google's golden signal

### ISSUE THREAD

**Issue by mfurquim** [labbsr0x/big-brother#2]
[Google's golden signal](https://landing.google.com/sre/sre-book/chapters/monitoring-distributed-systems/#xref_monitoring_golden-signals)

**Comment by abilioesteves** [comment]
Hi @mfurquim, could you please be more specific with regards to what the actual issue is? Do you have any change proposal you would like to discuss? Thanks!

**Comment by mfurquim** [comment]
@abilioesteves, what is the naming convention that will be given to recording rules?

Given this example in `/metrics`
```
request_seconds_count:irate{addr="/resource/test-0001",job="l1",method="DELETE",prsn="metrics-generator",status="2xx",type="http",instance=""} 0.6340519255155843 1570474761138
```

There is this expression to get the throughput (one of the golden signals):
```
sum(request_seconds_count:irate) without (job, instance)
```

But what is the name it should be given? Does `request_seconds:throughput` seem appropriate? I am aware of [Prometheus' best practices](https://prometheus.io/docs/practices/rules/), so maybe `request_seconds_count:throughput_irate` seems better?

**Comment by abilioesteves** [comment]
@mfurquim, why would we want to record such expression? This equation can easily be handled in runtime, by Grafana and Alerting rules.

**Comment by mfurquim** [comment]
For better maintainability of the project. If, for instance, there is a need to alter a label and there is a dozen of dashboards on Grafana, then we would only need to modify the expression once on the recording rule file, instead of modifying all the dashboards. In addition to that, the dashboards will load faster, due to the Prometheus not having to evaluate the query every time the dashboard requests it.

**Comment by abilioesteves** [comment]
> If, for instance, there is a need to alter a label and there is a dozen of dashboards on Grafana, then we would only need to modify the expression once on the recording rule file, instead of modifying all the dashboards

We are creating Big Brother under the guidance of a **Protocol** construction. This puts us with a harder **constraint** with regards to what we can actually change or not. The protocol as it sits right now, is generic enough to cover the first 3 rules of Google's Golden Signal. We should not be discussing strategies for maintainability at this point, but be discussing instead how the protocol needs to evolve to handle the 4th rule (saturation). Protocols, once released, are much harder to change and must follow due procedure. 

With this approach we detach the life cycle of the application from the protocol. The protocol can evolve hands-free and the application will do whatever it can to catch up.

> In addition to that, the dashboards will load faster, due to the Prometheus not having to evaluate the query every time the dashboard requests it.

Have you ever heard of [`Trickster`](https://github.com/Comcast/trickster)? It acts like a cache proxy for Prometheus, accelerating Grafana queries, for example.

--

On a third note, we should be very careful with how much data is being stored on our monitor. We have built an architecture that allows many application to be consistently observed by a single big brother instance. Storage is the most expensive component on big brother's architecture, and should always try to optimize it.

--

Do you have any suggestion on how we should evolve the Big Brother's protocol to handle the 4th google rule (saturation)? Thanks!

**Comment by mfurquim** [comment]
Oh, I get it now. I was mistakenly worried about making it faster, but is storage what I have to worry about. I will continue to build the Grafana's dashboard for the golden rules without the recording rules then.

--

> Have you ever heard of Trickster? It acts like a cache proxy for Prometheus, accelerating Grafana queries, for example.

Oh, cool, I haven't heard about it, no. I'll research more :)

--

> Do you have any suggestion on how we should evolve the Big Brother's protocol to handle the 4th google rule (saturation)? Thanks!

Well, not quite. I have been thinking about it since I read the [Golden Signals](https://landing.google.com/sre/sre-book/chapters/monitoring-distributed-systems/#xref_monitoring_golden-signals) and still haven't figured it out.
