### ISSUE TITLE
Create gorilla mux middleware

### ISSUE THREAD

**Issue by abilioesteves** [labbsr0x/big-brother#28]
Labbs' [Whisper project](https://github.com/labbsr0x/whisper) uses a self-created observability lib. We want to use the Big Brother's protocol, but there is no lib available. With that in mind, we should:

1. [x] Create a new labbsr0x repo;
2. [x] Create a valid `go module` lib that exposes the Big Brother metrics at a configurable endpoint and all the features the other libs provide;
3. [x] When done and tested, add this new lib as a submodule to this repo.

**Comment by abilioesteves** [comment]
@werberson, is [mux-monitor](https://github.com/labbsr0x/mux-monitor) done?

**Comment by werberson** [comment]
Not yet, I’m working on it.

**Comment by abilioesteves** [comment]
@werberson, please let me know we mux-monitor is ready.

**Comment by abilioesteves** [comment]
@werberson, any progress?

**Comment by abilioesteves** [comment]
https://github.com/labbsr0x/mux-monitor/releases/tag/v1.0.0-rc
