### ISSUE TITLE
Dev Chart

### ISSUE THREAD

**Issue by gutorc92** [labbsr0x/big-brother#31]
As we have made efforts to deploy cortex on k8s, we could create a chart to deploy a stack of test.

This stack will include generator-metrics, bb-promster and etcd. 
The chart have to  attend to the requirements:

- [x]  1 bb-promster for each generetor-metrics

- [x]  1 etcd deployment and service

- [x]  generetor's metrics replicas configurable

**Comment by abilioesteves** [comment]
Shouldn't we also include cortex in the chart?

**Comment by gutorc92** [comment]
Cortex already has its [chart](https://github.com/cortexproject/cortex-helm-chart) but the chart not includes deploy using [Cassandra](https://github.com/cortexproject/cortex-helm-chart/issues/5). We can help community trying to solve issue 5 on the cortex-helm-chart repo. Then, It is better to separate specific deploys of big-brother separated from cortex-helm-chart.

**Comment by abilioesteves** [comment]
I think we should create our own charts then, with all cortex services defined in it, making use of as much knowledge as possible from the [cortex charts](https://github.com/cortexproject/cortex-helm-chart) already created by the cortex team... With the lessons learned from it, we can then proceed with your suggestion to contribute to issue 5.

@KarineValenca is working on a chart for Cassandra, right? She may be able to help them...

**Comment by gutorc92** [comment]
We can fork the project of [cortex chart](https://github.com/cortexproject/cortex-helm-chart), if we can deploy with cassandra issue 5 is solved.

**Comment by abilioesteves** [comment]
Not sure I'm following... We would work on our chart in that fork?

**Comment by gutorc92** [comment]
Yes. We will have two repositories: one for bb-promster, metrics generator and etcd and other for just cortex.  On cortex chart, we can help community and make easier to deploy on bb arq 3.0.

**Comment by abilioesteves** [comment]
Understood. Please, proceed.

**Comment by abilioesteves** [comment]
@gutorc92, please remember to close this issue when you're done.

**Comment by abilioesteves** [comment]
@gutorc92, is this done?

**Comment by gutorc92** [comment]
Yes, it was done on [big-brother-chart](https://github.com/labbsr0x/big-brother-helm-chart).
