### ISSUE TITLE
Front-end proposal

### ISSUE THREAD

**Issue by gutorc92** [labbsr0x/big-brother#33]
The bb team needs to update targets on prometheus for some projects. This process is done by generating a file and copying it to prometheus container. Eventually, the big brother project will need those targets on a Etcd, a possible solution to help the bb team and keep the targets is create a front-end to interact to Etcd. Bb-bot project already has the endpoints to make operations on Etcd, then a solution will need just add more one endpoint to delete Ips for an app.  The front-end solution can be implemented on a lightweight framework like [Svelte](https://svelte.dev/). The requirements of front-end project will be:

- [ ] List apps

- [ ] List Ips for an app.

- [ ]  Add a Ip on the app

- [ ] Generete a json file to update prometheus with a giving number of Ips.

**Comment by abilioesteves** [comment]
We should definitely do it. But use react and material-ui, please. Given our constraints, I rather have a more bloated front that anyone can work on at any time, than a lean front that few people would be able to work overnight.

**Comment by abilioesteves** [comment]
Also, material and react can be very modular. No need to add redux, for example.
