### ISSUE TITLE
Review docker-compose and README components section

### ISSUE THREAD

**Issue by abilioesteves** [labbsr0x/big-brother#34]
Given the new components landscape for Big Brother, we should review our docker-compose and README.

**Comment by gutorc92** [comment]
I will add bb-manager to README and docker-compose.

**Comment by abilioesteves** [comment]
@gutorc92, @KarineValenca will take over this issue.

**Comment by KarineValenca** [comment]
- [ ] Add bb-manager service to docker-compose

- [ ] Remove monitor service and folder 

- [ ] Update README

**Comment by KarineValenca** [comment]
@abilioesteves In which repository we should keep the alerts created by @mfurquim inside the monitor folder? These alerts are really good and the monitor folder will be removed, so I think it's a good idea to keep them in another repo.

**Comment by abilioesteves** [comment]
I think the `bb-alertmanager` repo is the most appropriate place to put them.

**Comment by abilioesteves** [comment]
Sorry @KarineValenca. We should actually put it on the BB Promster project. My mistake.

**Comment by abilioesteves** [comment]
Fixed by @KarineValenca on #37
