### ISSUE TITLE
Add quarkus extension for Big Brother

### ISSUE THREAD

**Issue by CarlosPanarello** [labbsr0x/big-brother#45]
Marcelo Rubim and I, made a quarkus extension for Big Brother, it is in Rubim [repo](https://github.com/marcelorubim/quarkus-monitor)
We use the servlet-monitor as example to create this extension.
We think to move this project to labbsr0x repo, but some adjustments maybe necessary. 
Could you look if this project is suitable for Big Brother ?

Eu e o Marcelo Rubim fizemos uma extensão do quarkus para o Big Brother, esse projeto esta no [repo](https://github.com/marcelorubim/quarkus-monitor) do Rubim.
Usamos o servlet-monitor como exemplo para criar essa extensão.
Estamos pensando em mover esse projeto para o repositório do labbsr0x, talvez precise de alguns ajustes.
Vocês poderiam dar uma olhada no projeto e ver se ele esta de acordo com o padrões do Big Brother ?

**Comment by abilioesteves** [comment]
@CarlosPanarello, thank you for your contribution!

I have a few considerations already:

1. The english on the README should be double checked. There are some mistakes. And we can do that in Rubim's repo for now.

2. We should rewrite the commit history as I am seeing some sensitive information in the commit log, namely you employee key:

![image](https://user-images.githubusercontent.com/6494839/95220433-d7ca1500-07cc-11eb-93c0-de2c2b78d4be.png)

3. I don't see unit testing files. We should have a handful of tests just to make sure the lib have it's basic functions working.

@gilliardmacedo, could you see if their lib works as it should be? And if the way the lib was written in a compliant way with how people are writing applications with Quarkus?

**Comment by CarlosPanarello** [comment]
> @CarlosPanarello, thank you for your contribution!
> 
> I have a few considerations already:
> 
> 1. The english on the README should be double checked. There are some mistakes. And we can do that in Rubim's repo for now.
> 2. We should rewrite the commit history as I am seeing some sensitive information in the commit log, namely you employee key:
> 
> ![image](https://user-images.githubusercontent.com/6494839/95220433-d7ca1500-07cc-11eb-93c0-de2c2b78d4be.png)
> 
> 1. I don't see unit testing files. We should have a handful of tests just to make sure the lib have it's basic functions working properly.
> 
> @gilliardmacedo, could you see if their lib works as it should? And if the lib was written in a compliant way with how people are writing applications with Quarkus?

1 - I will review it in this weekend.
2 - I already corrected that.
3 - The test files is inside deployment project, there i made some tests for application_info and requests metrics, i need to add more tests for response-size and dependency metrics, right now they are in add_tests branch.

**Comment by abilioesteves** [comment]
@CarlosPanarello, please let me know in this thread when you finish tackling points 1 and 3. Thank you!

**Comment by abilioesteves** [comment]
@CarlosPanarello, any progress this week? Do you need any help?

**Comment by CarlosPanarello** [comment]
Yes, i just finished the tests. But i need to review the Readme.

**Comment by gilliardmacedo** [comment]
@abilioesteves I'm already using this lib. It works and is compliant.

**Comment by abilioesteves** [comment]
Thank you @gilliardmacedo! @CarlosPanarello, for this lib to be officially supported by labbsr0x, we require you to donate it to us. Just go to settings and then click on `Transfer` and type the name of our github organization `labbsr0x`.

Once you do that, I'll close this issue and update Big Brother's documentation.

**Comment by abilioesteves** [comment]
@CarlosPanarello, if you want we can also add the `quarkus-monitor` as a third-party lib.

**Comment by marcelorubim** [comment]
@abilioesteves I've just made the repository transfer. Thanks!

**Comment by abilioesteves** [comment]
Thank you @marcelorubim !
